name: Build and Deploy VuePress

on:
  push:
    branches: [ docs-master ]
  pull_request:
    branches: [ docs-master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: vue-press deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: master
        BUILD_SCRIPT: ls -la
        BUILD_DIR: .
